### ISSUE TITLE
Overall

### ISSUE THREAD

**Issue by Axkaban** [Alrefai/capstone-project-2-expresso#3]
Grade: **met requirements, exceeded expectations**

A 200 Ok!

Congratulations again! You have finished the intensive strong! 

If you want to learn more on destructuring here's a [good link ](http://2ality.com/2015/01/es6-destructuring.html), and [here's](https://github.com/getify/You-Dont-Know-JS/blob/master/README.md) a good source for expansion in some hard features of JS.

I hope you enjoyed the course! 

Best of luck!

**Comment by Alrefai** [comment]
Thanks for your valuable feedback and delightful review. I am honored!

I was not familiar with destructuring. I will learn more about it from the resources you provided.

This course was challenging. However, I really enjoyed it and learned a lot from it.

Best regards!
